"""create_vessels_voyages_daily_reports_tables

Revision ID: c73d52658f06
Revises: 
Create Date: 2026-06-02 23:27:18.380644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c73d52658f06'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vessels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vessel_name', sa.String(length=255), nullable=False),
    sa.Column('technical_manager', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vessels_vessel_name'), 'vessels', ['vessel_name'], unique=True)
    op.create_table('voyages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vessel_id', sa.Integer(), nullable=False),
    sa.Column('voyage_number', sa.String(length=100), nullable=True),
    sa.Column('departure_port', sa.String(length=255), nullable=True),
    sa.Column('arrival_port', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voyages_vessel_id'), 'voyages', ['vessel_id'], unique=False)
    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vessel_id', sa.Integer(), nullable=False),
    sa.Column('voyage_id', sa.Integer(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('utc_time', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.String(length=50), nullable=True),
    sa.Column('latitude_decimal', sa.Float(), nullable=True),
    sa.Column('longitude_decimal', sa.Float(), nullable=True),
    sa.Column('vessel_condition', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('report_source_type', sa.String(length=50), nullable=False),
    sa.Column('total_hsfo_consumption', sa.Float(), nullable=True),
    sa.Column('total_lsfo_consumption', sa.Float(), nullable=True),
    sa.Column('total_mgo_consumption', sa.Float(), nullable=True),
    sa.Column('hsfo_rob', sa.Float(), nullable=True),
    sa.Column('lsfo_rob', sa.Float(), nullable=True),
    sa.Column('mgo_rob', sa.Float(), nullable=True),
    sa.Column('distance_sailed', sa.Float(), nullable=True),
    sa.Column('speed_last_24hrs', sa.Float(), nullable=True),
    sa.Column('avg_speed', sa.Float(), nullable=True),
    sa.Column('me_rpm', sa.Float(), nullable=True),
    sa.Column('avg_slip', sa.Float(), nullable=True),
    sa.Column('beaufort_scale', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('draft_forward', sa.Float(), nullable=True),
    sa.Column('draft_aft', sa.Float(), nullable=True),
    sa.Column('me_cyl_oil_rob', sa.Float(), nullable=True),
    sa.Column('cyl_oil_consumption', sa.Float(), nullable=True),
    sa.Column('me_system_oil_rob', sa.Float(), nullable=True),
    sa.Column('me_system_oil_consumption', sa.Float(), nullable=True),
    sa.Column('ae_lo_rob', sa.Float(), nullable=True),
    sa.Column('ae_lo_consumption', sa.Float(), nullable=True),
    sa.Column('fw_rob', sa.Float(), nullable=True),
    sa.Column('ae1_running_hours', sa.Float(), nullable=True),
    sa.Column('ae2_running_hours', sa.Float(), nullable=True),
    sa.Column('ae3_running_hours', sa.Float(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.Column('source_file_name', sa.String(length=500), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ),
    sa.ForeignKeyConstraint(['voyage_id'], ['voyages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vessel_id', 'report_date', name='uq_vessel_report_date')
    )
    op.create_index('ix_vessel_report_date', 'daily_reports', ['vessel_id', 'report_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vessel_report_date', table_name='daily_reports')
    op.drop_table('daily_reports')
    op.drop_index(op.f('ix_voyages_vessel_id'), table_name='voyages')
    op.drop_table('voyages')
    op.drop_index(op.f('ix_vessels_vessel_name'), table_name='vessels')
    op.drop_table('vessels')
    # ### end Alembic commands ###
